default_language_version:
  python: python3
repos:
-   hooks:
      -   id: autoflake
          args:
            - --remove-all-unused-imports
            - --in-place
    repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
-   hooks:
      -   id: isort
          args:
            - --profile
            - black
    repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
-   hooks:
      -   id: black
    repo: https://github.com/psf/black
    rev: 21.9b0
-   hooks:
      -   id: mypy
          name: mypy
          entry: dmypy run -- src
          language: system
          pass_filenames: false
    repo: local
-   hooks:
      -   id: flake8
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
